apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      serviceAccountName: django-sa
      containers:
      - name: celery
        image: asia-south1-docker.pkg.dev/devopsdjango/django-repo/django-app:latest
        command: ["celery", "-A", "tutorials", "worker", "-l", "info"]
        env:
        - name: DB_NAME
          value: "main_db"                                  # ✅ terraform output
        - name: DB_USER
          value: "django_user"                              # ✅ terraform output
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        - name: DB_HOST
          value: "devopsdjango:asia-south1:postgres-instance"  # ✅ terraform output
        - name: DB_PORT
          value: "5432"
        - name: REDIS_HOST
          value: "10.249.52.84"                             # ✅ terraform output
        - name: REDIS_PORT
          value: "6379"
        - name: GCS_BUCKET
          value: "devopsdjango-django-bucket"               # ✅ terraform output
        - name: GOOGLE_CLOUD_PROJECT
          value: "devopsdjango"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/var/secrets/google/key.json"
        volumeMounts:
        - name: gcp-key
          mountPath: /var/secrets/google
          readOnly: true
      volumes:
      - name: gcp-key
        secret:
          secretName: gcp-sa-key
